server:
  port: 5006


spring:
  application:
    name: payment-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver


razorPay:
  api:
    key: "rzp_test_T2cEjfWVKqQSou"
    secret: "iAqA3TZif95jyjXpoflz3Ylt"


stripe:
  api:
    key: "sk_test_51TjXQZLab92K1hchDwpKUwLVdblEkJUGzMirOUjJFT9wIYou4ayLgUIjjkRLSLNg7ObOoNbYMyGckuHTgs5BzUj800Q1VMIiI0"



eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/