spring.application.name=payment-service

server.port=5006

spring.datasource.url=jdbc:mysql://localhost:3306/paymentdb_zen?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

stripe.api.key=your_stripe_secret_key

razorPay.api.key=rzp_test_T2cEjfWVKqQSou
razorPay.api.secret=iAqA3TZif95jyjXpoflz3Ylt

