server:
  port: 5006

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3303/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

razorPay:
  api:
    key: "rzp_test_..."
    secret: "..."

stripe:
  api:
    key: "sk_test_..."

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/