services:
  eureakaserver:
    image: "rithanyaa870/salon-eureka-server-com"
    ports:
      - "8070:7070"

    healthcheck:
      test: ["CMD-SHELL","surl --fail --silent eurekaserver:8070/actuator/health/readines | grep UP || exist 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    container_name: eurekaserver

    deploy:
      resources:
        limits:
          memory: 700m

    networks:
      zen:




