
server:
  port: 5002


spring:
  application:
    name: salon-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://salondb:3306/salondb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver


eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaserver:8070/eureka/